--- 
- name: run single telco test on openshift-ci
  hosts: registry.kni-qe-41.lab.eng.tlv2.redhat.com
  remote_user: kni
  vars:
    kubeconfig: /home/kni/clusterconfigs/helix39/auth/kubeconfig
    ansible_ssh_private_key_file: "~/.ssh/my_key"
  tasks: 

    - name: verify ginkgo is installed
      ansible.builtin.shell: chdir=/home/kni/eco-gosystem/scripts ./install-ginkgo.sh

    - name: run single powermanagement test
      ansible.builtin.command: chdir=/home/kni/eco-gosystem/tests/ranfunc/powermanagement ginkgo --focus="Enable powersave at node level and then enable performance at node level"
      environment:
        KUBECONFIG_SPOKE1: "{{ kubeconfig }}"
        KUBECONFIG: "{{ kubeconfig }}"
        ECO_VERBOSE_LEVEL: 100
