---
- name: trigger telco-ran jenkins job
  hosts: localhost
  vars:
    username: "sobarzan"
    token: "1100801d3ed94b3864667929f4736f8ed8"
  tasks:
    - name: trigger telco-ran jenkins job 
      ansible.builtin.shell: 
        curl -k https://auto-jenkins-csb-kniqe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-far-edge-vran-deployment/buildWithParameters \
         --user {{ username }}:{{ token }} \
         --data LOCK_LABEL_HOST=registry.kni-qe-11.lab.eng.rdu2.redhat.com \
         --data VERSION=4.14 \
         --data DU_PULL_SPEC=quay.io/openshift-release-dev/ocp-release:4.14.10-x86_64 \
         --data ZTP_VERSION=4.14 \
         --data SPOKE_OPERATOR_IMAGES_SOURCE=brew \
         --data UPLOAD_METRICS=false \
         --data ZTP_SITECONFIG_REPO_BRANCH=helix59-4.14-acmgen-retest1 \
         --data ZTP_POLICIES_REPO_BRANCH=helix59-4.14-acmgen-retest1 