--- 
- name: run single telco test on openshift-ci
  hosts: kniqe41
  remote_user: kni
  vars:
    kubeconfig: /home/kni/clusterconfigs/helix41/auth/kubeconfig
    shared_dir: /tmp/secret
    repo_folder: /home/kni/eco-gosystem
    ecogosystem_repo: "https://github.com/shaior/eco-gosystem.git"
  tasks: 
    - name: clone eco-gosystem git repo
      ansible.builtin.git:
        repo: "{{ ecogosystem_repo }}"
        dest: "{{ repo_folder }}"
        version: telco-ci-init

    - name: verify ginkgo is installed
      ansible.builtin.shell: cd {{ repo_folder }}/scripts && ./install-ginkgo.sh

    - name: run single powermanagement test
      ansible.builtin.shell: cd {{ repo_folder }}/tests/ranfunc/powermanagement && ginkgo --focus="verifies expected kernel parameters with no workload hints specified in PerformanceProfile"
      environment:
        KUBECONFIG_SPOKE1: "{{ kubeconfig }}"
        KUBECONFIG: "{{ kubeconfig }}"
        ECO_VERBOSE_LEVEL: 100
      ignore_errors: true