--- 
- name: run single telco test on openshift-ci
  hosts: kniqe41
  remote_user: kni
  vars:
    kubeconfig: /home/kni/clusterconfigs/helix39/auth/kubeconfig
  tasks: 
    - name: verify ginkgo is installed
      ansible.builtin.shell: chdir=/home/kni/eco-gosystem/scripts ./install-ginkgo.sh

    - name: run single powermanagement test
      ansible.builtin.shell: cd /home/kni/eco-gosystem/tests/ranfunc/powermanagement && ginkgo --focus="verifies expected kernel parameters with no workload hints specified in PerformanceProfile" > /home/kni/job_log.yaml
      environment:
        KUBECONFIG_SPOKE1: "{{ kubeconfig }}"
        KUBECONFIG: "{{ kubeconfig }}"
        ECO_VERBOSE_LEVEL: 100
